openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://127.0.0.1:8000/api/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
    post:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
  /login:
        post:
          description: Lets a user post a new artist
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object 
                  required:
                    - phone
                    - password
                  properties:
                    phone:
                      type: string
                    password:
                      type: string

          responses:
            '200':
              description: Successfully created a new artist

            '400':
              description: Invalid request
              content:
                application/json:
                  schema:
                    type: object
                    properties:   
                      message:
                        type: string
      
